{% set name = "themis" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  
  path: ..

build:
  number: 1            
  

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.18
    - ninja
    - make
    - rust >=1.72
    - cargo-bundle-licenses
  host:
    - python {{ python }}
    - pip
    - setuptools >=68
    - seqan3 ==3.3.0
    - cxxopts >=2.2.0
    - catch2 ==2.*
    - zlib
    - bzip2
    - raptor ==3.*
    - pandas >=1.2.0
    - multitax >=1.3.1
    - genome_updater >=0.6.4
    - grep
    - coreutils
    - curl
    - diffutils
  run:
    - python
    - pandas >=1.2.0
    - multitax >=1.3.1
    - genome_updater >=0.6.4
    - grep
    - coreutils
    - curl
    - diffutils
    - zlib
    - bzip2
    - raptor ==3.*
    - fastp

test:
  requires:
    - python
  script: |
    themis -h

 

about:
  home: https://github.com/<your-org>/themis
  summary: "Themis: integrated metagenomic profiling with bundled ganon (C++ & Python) and ggcat (Rust)"
  license: GPL-3.0
  license_family: GPL3

extra:
  final: true
  copy_test_source_files: true
